name: Build and push
on:
    pull_request:
        branches:

    push:
        branches:
            - main
            - master
        tags-ignore:
            - v*

env:
    BUILDKIT_INLINE_CACHE: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1

jobs:
    setup:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Display Github event details
              continue-on-error: true
              run: |
                  echo "::group::Env"
                  env
                  echo "::endgroup::"

                  echo "::group::Github event"
                  cat "$GITHUB_EVENT_PATH" | jq -M .
                  echo "::endgroup::"

            - name: Build
              # TODO: only run for pushes, not tags
              run: docker build -t soulshake/app .

            - name: Retag
              # TODO: retag images on tag push
              run: |
                echo "Not implemented"

            - name: Run
              run: docker run hello-world

            - name: Push
              run: |
                echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --password-stdin -u soulshake
                docker push soulshake/app

            - name: Test our action
              uses: soulshake/sensemaker@master
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  repository: soulshake/sensemaker
                  event-type: deploy
                  args: '{"github": ${{ toJson(github) }}}'

