iname: Build and push
on:
    pull_request:
        branches:

    push:
        branches:
            - main
            - master
        tags-ignore:
            - v*

env:
    BUILDKIT_INLINE_CACHE: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1

jobs:
    setup:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Display Github event details
              continue-on-error: true
              run: |
                  echo "::group::Env"
                  env
                  echo "::endgroup::"

                  echo "::group::Github event"
                  cat "$GITHUB_EVENT_PATH" | jq -M .
                  echo "::endgroup::"

            - name: Build
              run: docker build -t soulshake/app .

            - name: Run
              run: docker run -ti hello-world

            - name: Push
              run: |
                echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --password-stdin -u soulshake
                docker push soulshake/app
